server:
  max-players:
    override: true
    value: 20
  motd:
    override: true
    messages:
      - "<red>Red MOTD"
      - "<green>Green MOTD"
      - "<blue>Blue MOTD"
      - "<#FF00FF>Purple MOTD"
      - "Multi-line\n<gold>Gold MOTD"
  pvp:
    override: false
    allowed: true
  broadcast-to-lan: false