name: "ServerSettings"
version: "0.0.4"
description: "Manage various server.properties entries without restarting your server!"
author: "Hannah"
website: "https://winnpixie.xyz/"
main: "io.github.winnpixie.serversettings.ServerSettings"
api-version: 1.16

commands:
  server-settings:
    permission: server-settings.command
    aliases: [ "serversettings", "ss" ]
    description: "Execute various ServerSettings actions."
    usage: "/server-settings [subcommand] ..."