name: "ServerSettings"
version: ${project.version}
description: "Manage various server.properties entries without restarting your server!"
author: "winnpixie"
website: "https://winnpixie.github.io/"
main: "io.github.winnpixie.serversettings.ServerSettings"
api-version: 1.21

commands:
  server-settings:
    permission: server-settings.command
    aliases: [ "serversettings", "ss" ]
    description: "Execute various ServerSettings actions."
    usage: "/serversettings [subcommand] ..."